/**
 * Types shared between the web app, the worker, and (later) the mobile app.
 *
 * The `Database` type below mirrors `/supabase/migrations` by hand. It can be
 * regenerated from the live database instead, once the migration is applied:
 *
 *   npx supabase gen types typescript --project-id <ref> --schema public
 *
 * If you change a migration, change this file in the same commit.
 */

export const SUBSCRIPTION_TIERS = ['free', 'pro', 'business'] as const;
export type SubscriptionTier = (typeof SUBSCRIPTION_TIERS)[number];

export const DOCUMENT_SOURCE_TYPES = [
  'manual_upload',
  'forwarded_email',
] as const;
export type DocumentSourceType = (typeof DOCUMENT_SOURCE_TYPES)[number];

export const DOCUMENT_STATUSES = [
  'processing',
  'ready',
  'needs_review',
  'failed',
  'quarantined',
] as const;
export type DocumentStatus = (typeof DOCUMENT_STATUSES)[number];

/**
 * Slug of the permanent system category that low-confidence AI results are
 * filed into. The app layer must refuse to rename or delete it.
 */
export const NEEDS_REVIEW_CATEGORY_SLUG = 'needs-review';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Structured facts the AI classifier pulls out of a document, alongside its
 * category guess and summary. Any of the three may be null when the
 * document simply doesn't contain that kind of information.
 */
export type DocumentAiEntities = {
  vendor: string | null;
  amount: string | null;
  date: string | null;
};

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          stripe_customer_id: string | null;
          subscription_tier: string;
          storage_limit_bytes: number;
          inbound_address_token: string;
          created_at: string;
        };
        // Only `id` and `display_name` are writable from a user's session; the
        // remaining columns are revoked at the database level and set by
        // trusted server-side code only.
        Insert: {
          id: string;
          display_name?: string | null;
        };
        Update: {
          display_name?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          icon: string | null;
          is_system_default: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          icon?: string | null;
          is_system_default?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          slug?: string;
          icon?: string | null;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'categories_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      documents: {
        Row: {
          id: string;
          user_id: string;
          category_id: string | null;
          source_type: string;
          source_message_id: string | null;
          original_filename: string;
          mime_type: string;
          file_size_bytes: number;
          storage_key: string;
          checksum_sha256: string;
          ai_summary: string | null;
          ai_confidence: number | null;
          /** Vendor/amount/date pulled out by the classifier, or all-null. */
          ai_entities: Json | null;
          /**
           * Free-text category name the AI proposed that doesn't match any of
           * the user's existing categories yet. Never auto-created; a future
           * UI phase surfaces this as "AI suggests a new category: X".
           */
          ai_suggested_category: string | null;
          status: string;
          deleted_at: string | null;
          created_at: string;
          /** Generated by Postgres from the filename and summary; read-only. */
          search_vector: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          category_id?: string | null;
          source_type: string;
          source_message_id?: string | null;
          original_filename: string;
          mime_type: string;
          file_size_bytes: number;
          storage_key: string;
          checksum_sha256: string;
          ai_summary?: string | null;
          ai_confidence?: number | null;
          ai_entities?: Json | null;
          ai_suggested_category?: string | null;
          status?: string;
          deleted_at?: string | null;
          created_at?: string;
        };
        Update: {
          category_id?: string | null;
          ai_summary?: string | null;
          ai_confidence?: number | null;
          ai_entities?: Json | null;
          ai_suggested_category?: string | null;
          status?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'documents_category_id_fkey';
            columns: ['category_id'];
            isOneToOne: false;
            referencedRelation: 'categories';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'documents_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

type Tables = Database['public']['Tables'];

/**
 * Domain shapes used by app and worker code. These narrow the raw database
 * rows where the database only has a text column plus a check constraint.
 */
export type Profile = Omit<Tables['profiles']['Row'], 'subscription_tier'> & {
  subscription_tier: SubscriptionTier;
};

export type Category = Tables['categories']['Row'];

export type DocumentRecord = Omit<
  Tables['documents']['Row'],
  'source_type' | 'status' | 'search_vector' | 'ai_entities'
> & {
  source_type: DocumentSourceType;
  status: DocumentStatus;
  ai_entities: DocumentAiEntities | null;
};
